### PR TITLE
Fixing font-size for resposiveness

### PR DESCRIPTION
**Pull request by harshpalsinh05**
please accept it

### CODE REVIEW

**Comment by HNSharma-07** [comment]
modified font size.

**Comment by harshpalsinh05** [comment]
done it bro

**Review by HNSharma-07 — APPROVED** [review]

**Review by HNSharma-07 — CHANGES_REQUESTED** [review]
approved

**Comment by HNSharma-07** [comment]
added

**Comment by harshpalsinh05** [comment]
Thanks bro

**Review by HNSharma-07 — APPROVED** [review]

**Pull request merged**
